### ISSUE TITLE
Replicate Model?

### ISSUE THREAD

**Issue by krrishdholakia** [riverscuomo/cuomputer#11]
Hey @riverscuomo nice repo - curious, which replicate model do you use ?

**Comment by riverscuomo** [comment]
Thank you sir! 
I was using a custom model trained on images of me but recently switched back to the basic model which apparently is updated from time to time.
https://github.com/riverscuomo/cuomputer/blob/72d14a88b014bb6b8240562f07778d9b89009ca2/bot/scripts/is_request_for_replicate.py#L8
