### ISSUE TITLE
Roles Assigned by Users Without Neighbor Role

### ISSUE THREAD

**Issue by Mel01000001** [riverscuomo/cuomputer#16]
These users have the Musician role assigned, despite not having the Neighbor role.

First noticed 8 September, US time (dates on screenshots are AUS time).

![Screenshot_20230909_110143_Discord](https://github.com/riverscuomo/cuomputer/assets/144282154/da31b226-a834-4f4a-9b96-2d8160fe78ba)
![Screenshot_20230909_123110_Discord](https://github.com/riverscuomo/cuomputer/assets/144282154/6dde36ff-418a-4227-828f-efe0135f8a6b)

**Comment by riverscuomo** [comment]
Actually, maybe this is something that needs to be changed in my discord server's settings? Can you ask Ray?

**Comment by Mel01000001** [comment]
Sure.  Will shoot her a message now.

**Comment by Mel01000001** [comment]
Found 6 more occurances after looking in connect to mrn channel.  They all had the visitor + musician roles, nothing else.  I could DM 1-2 to find out what they did?

**Comment by Mel01000001** [comment]
Taylor updated the Creating Music topic in the new onboarding Channels and Roles area, so that the user gets the Musicians channel added to their sidebar instead of assigning the Musician role.  Since the update, it appears no new users have the Musician + Visitor roles.
